name: Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'
      - name: get ivy
        run: choco install ivy
      - name: install Ant
        run: ant -lib C:/Users/salma/.ant/lib dist
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml dist
  test:
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'
      - name: get ivy
        run: choco install ivy
      - name: install Ant
        run: ant -lib C:/Users/salma/.ant/lib test
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml test     
#   test:
#     needs: build
#     runs-on: windows-latest
    
#     steps:
#       - name: install Ant
#         run: ant -lib C:/Users/salma/.ant/lib test
#       - name: Build with Ant
#         run: ant -noinput -buildfile build.xml test
